hand macro expand this to make "candidate" set printing more useful.  However, Now no candidates are printed because the 'notes' are in a system header. :(
#include <tgmath-sofar.h>
 double foo2(short *x) {
  return acos(x);
}

t.c:10:10: error: no matching function for call to '__tg_acos'; candidates are:
  return acos(x);
         ^~~~
1 diagnostic generated.